#!/bin/bash

# Rebuilds the NixOS configuration

# exit on error
set -e

# go to config directory
pushd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null

# format nixfiles
if command -v alejandra &> /dev/null; then
    tmp=$(mktemp)
    alejandra . 1>/dev/null 2>"$tmp" || (cat "$tmp" && rm -f "$tmp" && false)
    rm -f "$tmp"
fi

# show diff
git add .
git diff -U0 HEAD

# confirm
read -p $'\e[33mbut would you lose? (Y/n/(d)iff): \e[0m' yn

# view diff in difftool
if ! [[ -z "$yn" ]] && [[ "$yn" == "d" ]]; then
    git difftool -U0 HEAD -y
    read -p $'\e[33mcontinue? (Y/n): \e[0m' yn
fi

# exit if not confirmed
if ! [[ -z "$yn" ]] && [[ "$yn" != "y" ]] && [[ "$yn" != "Y" ]]; then
    echo $'\e[31mthe one piece is not real :('
    exit 1
fi

echo $'\e[1m\e[96mnah, i\'d win\e[0m'

# stop plasma making .gtkrc-2.0
rm -f "$HOME/.gtkrc-2.0"

(
    set -o pipefail

    # use nom (nixos output monitor) if available
    if command -v nom &> /dev/null; then
        # rebuild
        sudo nixos-rebuild switch --flake '.#nixos' --impure --log-format internal-json -v |& nom --json
    else
        # initial rebuild (nom will be installed after this)
        sudo nixos-rebuild switch --flake '.#nixos' --impure
    fi
)

# commit
gen=$(nix-env --list-generations | grep 'current' | sed 's/^[^0-9]*//' | sed 's/[^0-9]*$//')
git commit -am "Generation $gen" > /dev/null

echo "operation completed successfully :)"
popd

